services:
  docker-registry:
    network_mode: host
    image: registry
    environment:
      - STORAGE_PATH=/var/lib/registry
      - REGISTRY_LOG_LEVEL=error
    volumes:
      - /tmp/registry:/var/lib/registry
  zookeeper:
    network_mode: host
    image: bobrik/zookeeper
    environment:
      - ZK_CONFIG=tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      - ZK_ID=1
  mesos-master:
    network_mode: host
    image: mesosphere/mesos-master:1.0.11.0.1-2.0.93.ubuntu1404
    environment:
      - MESOS_LOGGING_LEVEL=ERROR
      - MESOS_IP=127.0.0.1
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_CLUSTER=test
      - MESOS_REGISTRY=in_memory
  mesos-slave-0:
    network_mode: host
    image: lensa/mesos-slave:1.0.11.0.1-2.0.93.ubuntu1404
    environment:
      #- MESOS_LOGGING_LEVEL=ERROR
      - MESOS_IP=127.0.0.1
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_CONTAINERIZERS=mesos
      - MESOS_IMAGE_PROVIDERS=docker
      - MESOS_ISOLATION=filesystem/linux,docker/runtime
      - MESOS_DOCKER_REGISTRY=http://localhost:5000
      - MESOS_PORT=5051
      - MESOS_RESOURCES=cpus(*):0.5;mem(*):1024;ports(*):[11000-11999]
      - MESOS_WORK_DIR=/tmp/mesos
      ## To speed up provisioning images, default is copy
      # MESOS_IMAGE_PROVISIONER_BACKEND=aufs
      ## To enable docker containerizer too
      # MESOS_CONTAINERIZERS=mesos,docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      ## To cache docker downloaded images
      # /tmp/mesos/store/docker:/tmp/mesos/store/docker
      ## To enable docker containerizer
      # /usr/bin/docker:/usr/bin/docker
      # /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  mesos-slave-1:
    network_mode: host
    image: lensa/mesos-slave:1.0.11.0.1-2.0.93.ubuntu1404
    environment:
      #- MESOS_LOGGING_LEVEL=ERROR
      - MESOS_IP=127.0.0.1
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_CONTAINERIZERS=mesos
      - MESOS_IMAGE_PROVIDERS=docker
      - MESOS_ISOLATION=filesystem/linux,docker/runtime
      - MESOS_DOCKER_REGISTRY=http://localhost:5000
      - MESOS_PORT=5052
      - MESOS_RESOURCES=cpus(*):1.0;mem(*):2048;ports(*):[11000-11999]
      - MESOS_WORK_DIR=/tmp/mesos
      ## To speed up provisioning images, default is copy
      # MESOS_IMAGE_PROVISIONER_BACKEND=aufs
      ## To enable docker containerizer too
      # MESOS_CONTAINERIZERS=mesos,docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      ## To cache docker downloaded images
      # /tmp/mesos/store/docker:/tmp/mesos/store/docker
      ## To enable docker containerizer
      # /usr/bin/docker:/usr/bin/docker
      # /var/run/docker.sock:/var/run/docker.sock
    privileged: true


pipeline:
  docker:
    image: docker:dind
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t lensa/dask.mesos .
      - docker tag lensa/dask.mesos localhost:5000/lensa/dask.mesos
      - docker push localhost:5000/lensa/dask.mesos

  test:
    image: lensa/dask.mesos
    network_mode: host
    environment:
      - LIBPROCESS_IP=127.0.0.1
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - ZOOKEEPER_HOST=127.0.0.1:2181
    commands:
      - pip install -U -e .
      - pip install pytest pytest-mock
      - sleep 12324351245234
      - python setup.py test


# publish:
#   pypi:
#     repository: https://pypi.python.org/pypi
#     username: $$PYPI_USERNAME
#     password: $$PYPI_PASSWORD
#     distributions:
#       - sdist
#     when:
#       event: [tag]

#   docker:
#     username: $$DOCKERHUB_USERNAME
#     password: $$DOCKERHUB_PASSWORD
#     email: $$DOCKERHUB_EMAIL
#     repo: lensa/dask.mesos
#     file: Dockerfile
#     tag:
#       - $$TAG
#       - latest
#     when:
#       event: [tag]

#   docker:
#     username: $$DOCKERHUB_USERNAME
#     password: $$DOCKERHUB_PASSWORD
#     email: $$DOCKERHUB_EMAIL
#     repo: lensa/dask.mesos
#     file: Dockerfile
#     tag:
#       - master
#     when:
#       branch: master
